[package]
name = "delegation-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Sorin Petreasca <sorin.petreasca@dharitri.com>"]

[dev-dependencies]
[dependencies.delegation-mock]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.12.3"
