[package]
name = "liquid-staking-abi"
version = "0.0.0"
authors = ["Sorin Petreasca <sorin.petreasca@dharitri.com>"]
edition = "2021"
publish = false
[dependencies.liquid-staking]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.12.3"
